#!/usr/bin/env python3
"""
APLOMB. The Serum — PDP conversion-asset generator (BFL Flux 2 Pro).

Anchored to the established visual canon (Aplomb_Peptide_Serum_Photo_1.jpg:
frosted-glass 30 mL dropper, cream label "Aplomb / THE SERUM" + amber dot,
travertine slab, crumpled linen, bone-china dish, soft directional window
light, warm bone backdrop). Brand register: Aesop / Augustinus Bader / The
Ordinary — editorial, restrained, clinical.

Prompt canon (from design-scratch/bfl-tests/gen-canon-tests.py):
  Subject -> Action -> Style -> Context, ~55-70 words, identity in first
  tokens, NO inline negation, material/biological-texture language, specific
  camera + lens, descriptive directional light, prompt_upsampling=False.

Output -> website/assets/ (final destination). cwebp variants generated by
gen-webp-variants.sh afterwards.

Run:
  python3 website/scripts/gen-serum-assets.py --only serum-texture
  python3 website/scripts/gen-serum-assets.py            # all
"""
import argparse
import base64
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

API_KEY = os.environ.get("BFL_API_KEY")
if not API_KEY:
    secrets = Path.home() / ".claude" / "secrets.env"
    if secrets.exists():
        for line in secrets.read_text().splitlines():
            if line.startswith("BFL_API_KEY=") or line.startswith("export BFL_API_KEY="):
                API_KEY = line.split("=", 1)[1].strip().strip("'\"")
                break
if not API_KEY:
    sys.exit("BFL_API_KEY not set.")

BASE = "https://api.bfl.ai/v1"
ENDPOINT = "flux-2-pro"
HEADERS = {"x-key": API_KEY, "Content-Type": "application/json"}

REPO = Path("/Users/zacharypoll/Desktop/Documents/Claude Code/Get-Aplomb")
OUT_DIR = REPO / "website" / "assets"
CANON = REPO / "product-lines" / "peptide-serum" / "Aplomb_Peptide_Serum_Photo_1.jpg"

# Shared scene language so every asset reads as one shoot.
SCENE = ("warm bone-white backdrop, honey-toned travertine stone slab, "
         "crumpled natural linen, soft directional window light from "
         "camera-left with gentle falloff, shallow depth of field, "
         "editorial still-life photography, restrained Aesop register, "
         "Hasselblad X2D with 90mm f/2.8")

CANON_B64 = base64.b64encode(CANON.read_bytes()).decode() if CANON.exists() else None

ASSETS = [
    {
        "label": "serum-hero",
        "w": 1408, "h": 1056, "ref": True,
        "prompt": (
            "A 30 mL frosted matte-glass serum bottle with a matte-black "
            "dropper cap and a cream paper label reading 'Aplomb' in italic "
            "serif above a small amber dot and 'THE SERUM' in fine letter-"
            "spaced caps, standing centred on a honey travertine slab beside "
            "a folded linen cloth and a small olive sprig on a bone-china "
            "dish. " + SCENE + ". Visible glass frosting, paper label tooth, "
            "stone porosity, soft contact shadow."
        ),
    },
    {
        "label": "serum-texture",
        "w": 1408, "h": 1056, "ref": True,
        "prompt": (
            "Extreme macro of the matte-black glass dropper held just above "
            "the bottle mouth, one clear faintly-amber serum droplet "
            "suspended at the pipette tip catching the window light, the "
            "frosted bottle soft behind it. " + SCENE + ". Visible meniscus "
            "curvature, subsurface light through the droplet, fine glass "
            "reflection, dust-free clinical clarity."
        ),
    },
    {
        "label": "serum-in-use",
        "w": 1024, "h": 1280, "ref": False,
        "prompt": (
            "An extremely attractive woman in her late thirties with "
            "striking bone structure and luminous bare skin, eyes lowered, "
            "pressing two serum drops along her jawline and neck with her "
            "fingertips, calm composed expression. Editorial beauty "
            "photography, soft north-window light from camera-right with "
            "gentle falloff, warm bone tones, visible pores, subsurface "
            "scattering, fine vellus hair, single catchlight. Sony A7IV with "
            "85mm f/1.8."
        ),
    },
    {
        "label": "serum-flatlay",
        "w": 1408, "h": 1056, "ref": True,
        "prompt": (
            "Overhead flat-lay of the frosted 'Aplomb THE SERUM' dropper "
            "bottle laid on folded linen on a honey travertine slab, a "
            "scattering of centella leaves and a halved kakadu plum and a "
            "short licorice root arranged with editorial restraint, a bone-"
            "china dish at the corner. " + SCENE + ". Visible leaf veining, "
            "stone grain, linen weave, soft even daylight."
        ),
    },
    {
        "label": "serum-ingredients",
        "w": 1408, "h": 1056, "ref": False,
        "prompt": (
            "Editorial botanical still-life: a sprig of fresh centella "
            "asiatica, a single kakadu plum, a curl of licorice root and a "
            "bearberry leaf cluster laid in a quiet row on a honey "
            "travertine slab beside folded linen. " + SCENE + ". Visible "
            "leaf veining, fruit skin texture, root fibre, soft shadow, "
            "muted natural colour."
        ),
    },
]


def post_json(path, payload):
    req = urllib.request.Request(
        f"{BASE}/{path}", data=json.dumps(payload).encode("utf-8"),
        headers=HEADERS, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read())
    except urllib.error.HTTPError as e:
        return {"_http_error": e.code, "_body": e.read().decode(errors="replace")}


def poll(polling_url, request_id, label):
    url = polling_url or f"{BASE}/get_result?id={request_id}"
    deadline = time.time() + 300
    while time.time() < deadline:
        req = urllib.request.Request(url, headers={"x-key": API_KEY})
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.loads(r.read())
        s = data.get("status")
        if s == "Ready":
            sample = (data.get("result") or {}).get("sample")
            if not sample:
                raise RuntimeError(f"[{label}] Ready but no sample")
            return sample
        if s in ("Request Moderated", "Content Moderated"):
            print(f"  [{label}] MODERATED: {s}")
            return None
        if s in ("Error", "Failed"):
            raise RuntimeError(f"[{label}] status={s}: {data}")
        print(f"  [{label}] status={s} -- polling...")
        time.sleep(2)
    raise RuntimeError(f"[{label}] timed out")


def download(url, out):
    with urllib.request.urlopen(url, timeout=60) as r:
        out.write_bytes(r.read())
    print(f"  -> wrote {out.name} ({out.stat().st_size // 1024} KB)")


def gen(a):
    out = OUT_DIR / f"{a['label']}.jpg"
    payload = {
        "prompt": a["prompt"], "width": a["w"], "height": a["h"],
        "prompt_upsampling": False,
    }
    use_ref = a.get("ref") and CANON_B64
    if use_ref:
        payload["input_image"] = CANON_B64
    wc = len(a["prompt"].split())
    print(f"[{a['label']}] {ENDPOINT} {a['w']}x{a['h']} "
          f"({wc} words, ref={'yes' if use_ref else 'no'})")
    resp = post_json(ENDPOINT, payload)
    if "_http_error" in resp:
        print(f"  [{a['label']}] HTTP {resp['_http_error']}: {resp['_body'][:300]}")
        return False
    sample = poll(resp.get("polling_url", ""), resp["id"], a["label"])
    if sample is None:
        return False
    download(sample, out)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="run one label, e.g. 'serum-texture'")
    args = ap.parse_args()
    targets = [a for a in ASSETS if (args.only is None or a["label"] == args.only)]
    if not targets:
        sys.exit("no match. Available: " + ", ".join(a["label"] for a in ASSETS))
    bad = []
    for a in targets:
        if not gen(a):
            bad.append(a["label"])
    print(f"\nDone. {len(targets) - len(bad)} / {len(targets)} succeeded.")
    if bad:
        print(f"Failed/moderated: {', '.join(bad)}")


if __name__ == "__main__":
    main()
