"""
Trace the plumb-bob mark from Logo Designs/02-plumb-line-mark.jpg using potrace.

Pipeline:
  1. Crop the source JPG to the line + bob region.
  2. Convert to a high-contrast black-and-white PBM (amber -> black on white).
  3. Run potrace --svg to produce a clean cubic-bezier path.
  4. Restyle and write aplomb-mark.svg + _mark_data.py for _build_logo.py.
"""

import os
import re
import subprocess
import cv2
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_JPG = os.path.normpath(os.path.join(HERE, "..", "..", "Logo Designs", "02-plumb-line-mark.jpg"))
DUMP_DIR = os.path.join(HERE, "_trace_dump")
os.makedirs(DUMP_DIR, exist_ok=True)

AMBER = "#7a3d14"


def write_pbm_p4(path, bits, w, h):
    """Write a P4 (raw binary) PBM file."""
    row_bytes = (w + 7) // 8
    out = bytearray()
    for r in range(h):
        for col_byte in range(row_bytes):
            byte = 0
            for bit in range(8):
                col = col_byte * 8 + bit
                if col < w and bits[r, col]:
                    byte |= 1 << (7 - bit)
            out.append(byte)
    with open(path, "wb") as f:
        f.write(f"P4\n{w} {h}\n".encode())
        f.write(out)


def main():
    img = cv2.imread(SRC_JPG)
    print(f"Source: {SRC_JPG} -> shape {img.shape}")

    crop_y0, crop_y1 = 150, 580
    crop_x0, crop_x1 = 440, 580
    crop = img[crop_y0:crop_y1, crop_x0:crop_x1]
    cv2.imwrite(os.path.join(DUMP_DIR, "01_crop.png"), crop)
    H, W = crop.shape[:2]
    print(f"Crop size: {W}x{H}")

    gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
    _, mask = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    mask_closed = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((2, 2), np.uint8), iterations=1)
    cv2.imwrite(os.path.join(DUMP_DIR, "02_threshold.png"), mask_closed)

    pbm_path = os.path.join(DUMP_DIR, "03_input.pbm")
    inverted = (255 - mask_closed) // 255
    write_pbm_p4(pbm_path, inverted, W, H)

    out_svg = os.path.join(DUMP_DIR, "04_potrace.svg")
    cmd = [
        "/opt/homebrew/bin/potrace",
        "--svg",
        "--turdsize", "2",
        "--alphamax", "1.0",
        "--opttolerance", "0.15",
        "--output", out_svg,
        pbm_path,
    ]
    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)
    print(f"Potrace wrote {out_svg}")

    with open(out_svg) as f:
        svg = f.read()

    vb_match = re.search(r'viewBox="([^"]+)"', svg)
    path_match = re.search(r'<path d="([^"]+)"', svg)
    if not vb_match or not path_match:
        raise RuntimeError("Could not parse potrace SVG output")

    vb_str = vb_match.group(1)
    raw_path_d = path_match.group(1)
    tx_match = re.search(r'<g transform="([^"]+)"', svg)
    transform = tx_match.group(1) if tx_match else ""

    styled = re.sub(r'fill="[^"]*"', f'fill="{AMBER}"', svg, count=1)
    styled = re.sub(r'<svg width="[^"]*" height="[^"]*"', '<svg', styled)
    styled = styled.replace('<svg', '<svg role="img" aria-label="Aplomb mark"', 1)
    styled = styled.replace(
        f'viewBox="{vb_str}">',
        f'viewBox="{vb_str}"><title>Aplomb mark</title>',
        1,
    )
    styled = re.sub(r'<!--.*?-->\s*', '', styled, flags=re.S)

    out_file = os.path.join(HERE, "aplomb-mark.svg")
    with open(out_file, "w") as f:
        f.write(styled)
    print(f"Wrote {out_file}  ({os.path.getsize(out_file)} bytes)")

    vb_tuple = tuple(float(x) for x in vb_str.split())
    with open(os.path.join(HERE, "_mark_data.py"), "w") as f:
        f.write("# Auto-generated by _trace_mark.py - do not hand-edit.\n")
        f.write(f"VIEWBOX = {vb_tuple!r}  # (minx, miny, w, h)\n")
        f.write(f"TRANSFORM = {transform!r}\n")
        f.write(f"PATH_D = {raw_path_d!r}\n")
    print("Wrote _mark_data.py for _build_logo.py to consume")


if __name__ == "__main__":
    main()
